package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PatientSource generated by hbm2java
 */
public class PatientSource  implements java.io.Serializable {


     private Integer patientSourceId;
     private String patientSourceName;
     private String MFL_Code;

    public String getMFL_Code() {
        return MFL_Code;
    }

    public void setMFL_Code(String MFL_Code) {
        this.MFL_Code = MFL_Code;
    }
     private Set persons = new HashSet(0);

    public PatientSource() {
    }

    public PatientSource(String patientSourceName, Set persons, String MFL_Code) {
       this.patientSourceName = patientSourceName;
       this.persons = persons;
       this.MFL_Code = MFL_Code;
    }
    
    public PatientSource(String patientSourceName, Set persons) {
       this.patientSourceName = patientSourceName;
       this.persons = persons;
    }
   
    public Integer getPatientSourceId() {
        return this.patientSourceId;
    }
    
    public void setPatientSourceId(Integer patientSourceId) {
        this.patientSourceId = patientSourceId;
    }
    public String getPatientSourceName() {
        return this.patientSourceName;
    }
    
    public void setPatientSourceName(String patientSourceName) {
        this.patientSourceName = patientSourceName;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }




}


